# Tensor in PyTorch
In `pytorch`, we use `torch.Tensor` object to represent data matrix. It is a lot like `numpy` array but not quite the same. `torch` provide APIs to easily convert data between `numpy` array and `torch.Tensor`. Let's play a little bit.

In [1]:
from __future__ import print_function
import numpy as np
import torch

In [2]:
# prompt: generate 1 to 9 numbers 3 x3 matrix and a a 3 X 1 vector 10 to 12

import numpy as np
data = np.arange(1, 10).reshape(3, 3)

vector = np.arange(10, 13).reshape(3, 1)

torch_data = torch.from_numpy(data)
torch_data

torch_vector = torch.from_numpy(vector)
torch_vector

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[10],
       [11],
       [12]])